name: Deploy Angular Application

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: self-hosted  # This specifies a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust to your needs

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build -- --prod  # Adjust for your production build or other configurations

      - name: Deploy to server
        run: |
          cp -R ./dist/* /var/www/html/  # Adjust path
