name: Deploy to Windows Web Server

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
           npm install
      - name: Build project
        run: |
          npm run build
      - name: Deploy to server
        run: |
          cp -R /inetpub/wwwroot  # Adjust path
